/* eslint-disable @typescript-eslint/no-explicit-any */
import { NextRequest, NextResponse } from "next/server";
import { getAuthContext } from "@/lib/middleware/auth";
import { requireOrgAdmin } from "@/lib/middleware/adminGuard";
import { createAdminClient } from "@/lib/supabase/server";

// GET    /api/invites/[token]  — validate a single invite by token or UUID
// DELETE /api/invites/[token]  — admin revokes an invite
// POST   /api/invites/[token]/accept — handled by accept/route.ts

export async function GET(
  _req: NextRequest,
  { params }: { params: Promise<{ token: string }> }
) {
  const { token } = await params;
  const supabase   = createAdminClient();

  // The token column holds a 48-char hex string generated by gen_random_bytes(24).
  // The id column is a UUID.  If we blindly include id.eq.<hex> in the .or() filter,
  // PostgREST tries to cast the hex string to UUID, fails, and the whole query returns
  // null — causing a false "Invite Not Found".  Only add id.eq when the value is a
  // real UUID (contains dashes and is 36 chars long).
  const isUuid = /^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i.test(token);
  const orFilter = isUuid
    ? `id.eq.${token},token.eq.${token}`
    : `token.eq.${token}`;

  const { data: invite, error: fetchErr } = await (supabase as any)
    .from("invites")
    .select("id, org_id, role, uses_left, expires_at, created_at, invited_email, organizations(name, slug)")
    .or(orFilter)
    .maybeSingle() as { data: Record<string, unknown> | null; error: unknown };

  if (fetchErr) {
    console.error("[invites/token] fetch error:", JSON.stringify(fetchErr));
  }

  if (!invite) {
    return NextResponse.json(
      { error: { code: "NOT_FOUND", message: "Invite not found." } },
      { status: 404 }
    );
  }

  const isExpired   = new Date(invite.expires_at as string) < new Date();
  const isExhausted = invite.uses_left !== null && (invite.uses_left as number) <= 0;

  return NextResponse.json({
    data: {
      ...invite,
      is_valid:   !isExpired && !isExhausted,
      is_expired: isExpired,
    },
  });
}

export async function DELETE(
  _req: NextRequest,
  { params }: { params: Promise<{ token: string }> }
) {
  const auth  = await getAuthContext();
  const guard = requireOrgAdmin(auth);
  if (guard) return guard;

  const { token } = await params;
  const supabase   = createAdminClient();

  const isUuid = /^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i.test(token);
  const orFilter = isUuid
    ? `id.eq.${token},token.eq.${token}`
    : `token.eq.${token}`;

  const { error } = await (supabase as any)
    .from("invites")
    .delete()
    .or(orFilter)
    .eq("org_id", auth!.orgId);

  if (error) {
    return NextResponse.json(
      { error: { code: "DB_ERROR", message: "Failed to revoke invite." } },
      { status: 500 }
    );
  }

  return NextResponse.json({ data: { revoked: true }, meta: { org_id: auth!.orgId } });
}
